// Code generated by protoc-gen-go.
// source: Game.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	Game.proto

It has these top-level messages:
	Game
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Game struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}

type Game_BaseRole struct {
	PlayerId         *int32  `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	Nick             *string `protobuf:"bytes,2,req,name=nick" json:"nick,omitempty"`
	HeroId           *int32  `protobuf:"varint,3,req,name=hero_id" json:"hero_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_BaseRole) Reset()         { *m = Game_BaseRole{} }
func (m *Game_BaseRole) String() string { return proto.CompactTextString(m) }
func (*Game_BaseRole) ProtoMessage()    {}

func (m *Game_BaseRole) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *Game_BaseRole) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *Game_BaseRole) GetHeroId() int32 {
	if m != nil && m.HeroId != nil {
		return *m.HeroId
	}
	return 0
}

// pid = 1001	客户端发送注册角色信息
type Game_RegisterRole struct {
	Info             *Game_BaseRole `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Game_RegisterRole) Reset()         { *m = Game_RegisterRole{} }
func (m *Game_RegisterRole) String() string { return proto.CompactTextString(m) }
func (*Game_RegisterRole) ProtoMessage()    {}

func (m *Game_RegisterRole) GetInfo() *Game_BaseRole {
	if m != nil {
		return m.Info
	}
	return nil
}

// pid = 1001 服务器返回 角色注册信息
type Game_RegisterRoleResult struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_RegisterRoleResult) Reset()         { *m = Game_RegisterRoleResult{} }
func (m *Game_RegisterRoleResult) String() string { return proto.CompactTextString(m) }
func (*Game_RegisterRoleResult) ProtoMessage()    {}

func (m *Game_RegisterRoleResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// pid = 1002 获取角色信息
type Game_GetRoleInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_GetRoleInfo) Reset()         { *m = Game_GetRoleInfo{} }
func (m *Game_GetRoleInfo) String() string { return proto.CompactTextString(m) }
func (*Game_GetRoleInfo) ProtoMessage()    {}

type Game_Attribute struct {
	Level            *int32  `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
	Exp              *int32  `protobuf:"varint,3,opt,name=exp" json:"exp,omitempty"`
	Hp               *int32  `protobuf:"varint,2,opt,name=hp" json:"hp,omitempty"`
	PhysicalDef      []int32 `protobuf:"varint,4,rep,name=physical_def" json:"physical_def,omitempty"`
	MagicDef         []int32 `protobuf:"varint,5,rep,name=magic_def" json:"magic_def,omitempty"`
	PhysicalDamage   []int32 `protobuf:"varint,6,rep,name=physical_damage" json:"physical_damage,omitempty"`
	MagicDamage      []int32 `protobuf:"varint,7,rep,name=magic_damage" json:"magic_damage,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_Attribute) Reset()         { *m = Game_Attribute{} }
func (m *Game_Attribute) String() string { return proto.CompactTextString(m) }
func (*Game_Attribute) ProtoMessage()    {}

func (m *Game_Attribute) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Game_Attribute) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *Game_Attribute) GetHp() int32 {
	if m != nil && m.Hp != nil {
		return *m.Hp
	}
	return 0
}

func (m *Game_Attribute) GetPhysicalDef() []int32 {
	if m != nil {
		return m.PhysicalDef
	}
	return nil
}

func (m *Game_Attribute) GetMagicDef() []int32 {
	if m != nil {
		return m.MagicDef
	}
	return nil
}

func (m *Game_Attribute) GetPhysicalDamage() []int32 {
	if m != nil {
		return m.PhysicalDamage
	}
	return nil
}

func (m *Game_Attribute) GetMagicDamage() []int32 {
	if m != nil {
		return m.MagicDamage
	}
	return nil
}

type Game_HangUpInfo struct {
	Type             *int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Id               *int32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Count            *int32 `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game_HangUpInfo) Reset()         { *m = Game_HangUpInfo{} }
func (m *Game_HangUpInfo) String() string { return proto.CompactTextString(m) }
func (*Game_HangUpInfo) ProtoMessage()    {}

func (m *Game_HangUpInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Game_HangUpInfo) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Game_HangUpInfo) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

// pid = 1002 角色返回
type Game_RoleInfoResult struct {
	BaseRole         *Game_BaseRole     `protobuf:"bytes,1,opt,name=base_role" json:"base_role,omitempty"`
	Attribute        *Game_Attribute    `protobuf:"bytes,2,opt,name=attribute" json:"attribute,omitempty"`
	HangUpInfo       []*Game_HangUpInfo `protobuf:"bytes,3,rep,name=hang_up_info" json:"hang_up_info,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Game_RoleInfoResult) Reset()         { *m = Game_RoleInfoResult{} }
func (m *Game_RoleInfoResult) String() string { return proto.CompactTextString(m) }
func (*Game_RoleInfoResult) ProtoMessage()    {}

func (m *Game_RoleInfoResult) GetBaseRole() *Game_BaseRole {
	if m != nil {
		return m.BaseRole
	}
	return nil
}

func (m *Game_RoleInfoResult) GetAttribute() *Game_Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Game_RoleInfoResult) GetHangUpInfo() []*Game_HangUpInfo {
	if m != nil {
		return m.HangUpInfo
	}
	return nil
}
