// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol.proto

It has these top-level messages:
	Account
	Game
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type AccountMsgID int32

const (
	// 客户端与账号服务器之间的数据
	AccountMsgID_Msg_GetType        AccountMsgID = 0
	AccountMsgID_Msg_RegisterPlayer AccountMsgID = 1
	AccountMsgID_Msg_RegisterResult AccountMsgID = 2
	AccountMsgID_Msg_LoginInfo      AccountMsgID = 3
	AccountMsgID_Msg_LoginResult    AccountMsgID = 4
	// 账号服务器与游戏服务器之间的通信
	AccountMsgID_Msg_GetGameAccount AccountMsgID = 100
	AccountMsgID_Msg_GameResult     AccountMsgID = 101
	AccountMsgID_Msg_NoteGame       AccountMsgID = 102
)

var AccountMsgID_name = map[int32]string{
	0:   "Msg_GetType",
	1:   "Msg_RegisterPlayer",
	2:   "Msg_RegisterResult",
	3:   "Msg_LoginInfo",
	4:   "Msg_LoginResult",
	100: "Msg_GetGameAccount",
	101: "Msg_GameResult",
	102: "Msg_NoteGame",
}
var AccountMsgID_value = map[string]int32{
	"Msg_GetType":        0,
	"Msg_RegisterPlayer": 1,
	"Msg_RegisterResult": 2,
	"Msg_LoginInfo":      3,
	"Msg_LoginResult":    4,
	"Msg_GetGameAccount": 100,
	"Msg_GameResult":     101,
	"Msg_NoteGame":       102,
}

func (x AccountMsgID) Enum() *AccountMsgID {
	p := new(AccountMsgID)
	*p = x
	return p
}
func (x AccountMsgID) String() string {
	return proto.EnumName(AccountMsgID_name, int32(x))
}
func (x *AccountMsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AccountMsgID_value, data, "AccountMsgID")
	if err != nil {
		return err
	}
	*x = AccountMsgID(value)
	return nil
}

type GameMsgID int32

const (
	GameMsgID_Game_Msg_GetType            GameMsgID = 1000
	GameMsgID_Game_Msg_RegisterRole       GameMsgID = 1001
	GameMsgID_Game_Msg_RegisterRoleResult GameMsgID = 1002
	GameMsgID_Game_Msg_GetRoleInfo        GameMsgID = 1003
	GameMsgID_Game_Msg_RoleInfoResult     GameMsgID = 1004
)

var GameMsgID_name = map[int32]string{
	1000: "Game_Msg_GetType",
	1001: "Game_Msg_RegisterRole",
	1002: "Game_Msg_RegisterRoleResult",
	1003: "Game_Msg_GetRoleInfo",
	1004: "Game_Msg_RoleInfoResult",
}
var GameMsgID_value = map[string]int32{
	"Game_Msg_GetType":            1000,
	"Game_Msg_RegisterRole":       1001,
	"Game_Msg_RegisterRoleResult": 1002,
	"Game_Msg_GetRoleInfo":        1003,
	"Game_Msg_RoleInfoResult":     1004,
}

func (x GameMsgID) Enum() *GameMsgID {
	p := new(GameMsgID)
	*p = x
	return p
}
func (x GameMsgID) String() string {
	return proto.EnumName(GameMsgID_name, int32(x))
}
func (x *GameMsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameMsgID_value, data, "GameMsgID")
	if err != nil {
		return err
	}
	*x = GameMsgID(value)
	return nil
}

type Account struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}

type Account_GetType struct {
	Pid              *AccountMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.AccountMsgID" json:"pid,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Account_GetType) Reset()         { *m = Account_GetType{} }
func (m *Account_GetType) String() string { return proto.CompactTextString(m) }
func (*Account_GetType) ProtoMessage()    {}

func (m *Account_GetType) GetPid() AccountMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return AccountMsgID_Msg_GetType
}

// 客户端消息
type Account_LoginInfo struct {
	Pid              *AccountMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.AccountMsgID,def=3" json:"pid,omitempty"`
	Playername       *string       `protobuf:"bytes,2,opt,name=playername" json:"playername,omitempty"`
	Passworld        *string       `protobuf:"bytes,3,opt,name=passworld" json:"passworld,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Account_LoginInfo) Reset()         { *m = Account_LoginInfo{} }
func (m *Account_LoginInfo) String() string { return proto.CompactTextString(m) }
func (*Account_LoginInfo) ProtoMessage()    {}

const Default_Account_LoginInfo_Pid AccountMsgID = AccountMsgID_Msg_LoginInfo

func (m *Account_LoginInfo) GetPid() AccountMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Account_LoginInfo_Pid
}

func (m *Account_LoginInfo) GetPlayername() string {
	if m != nil && m.Playername != nil {
		return *m.Playername
	}
	return ""
}

func (m *Account_LoginInfo) GetPassworld() string {
	if m != nil && m.Passworld != nil {
		return *m.Passworld
	}
	return ""
}

type Account_LoginResult struct {
	Pid              *AccountMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.AccountMsgID,def=4" json:"pid,omitempty"`
	Result           *int32        `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	Gameserver       *string       `protobuf:"bytes,3,opt,name=gameserver" json:"gameserver,omitempty"`
	PlayerId         *int32        `protobuf:"varint,4,opt,name=player_id" json:"player_id,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Account_LoginResult) Reset()         { *m = Account_LoginResult{} }
func (m *Account_LoginResult) String() string { return proto.CompactTextString(m) }
func (*Account_LoginResult) ProtoMessage()    {}

const Default_Account_LoginResult_Pid AccountMsgID = AccountMsgID_Msg_LoginResult

func (m *Account_LoginResult) GetPid() AccountMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Account_LoginResult_Pid
}

func (m *Account_LoginResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *Account_LoginResult) GetGameserver() string {
	if m != nil && m.Gameserver != nil {
		return *m.Gameserver
	}
	return ""
}

func (m *Account_LoginResult) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type Account_RegisterPlayer struct {
	Pid              *AccountMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.AccountMsgID,def=1" json:"pid,omitempty"`
	Playername       *string       `protobuf:"bytes,2,opt,name=playername" json:"playername,omitempty"`
	Passworld        *string       `protobuf:"bytes,3,opt,name=passworld" json:"passworld,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Account_RegisterPlayer) Reset()         { *m = Account_RegisterPlayer{} }
func (m *Account_RegisterPlayer) String() string { return proto.CompactTextString(m) }
func (*Account_RegisterPlayer) ProtoMessage()    {}

const Default_Account_RegisterPlayer_Pid AccountMsgID = AccountMsgID_Msg_RegisterPlayer

func (m *Account_RegisterPlayer) GetPid() AccountMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Account_RegisterPlayer_Pid
}

func (m *Account_RegisterPlayer) GetPlayername() string {
	if m != nil && m.Playername != nil {
		return *m.Playername
	}
	return ""
}

func (m *Account_RegisterPlayer) GetPassworld() string {
	if m != nil && m.Passworld != nil {
		return *m.Passworld
	}
	return ""
}

type Account_RegisterResult struct {
	Pid              *AccountMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.AccountMsgID,def=2" json:"pid,omitempty"`
	Result           *int32        `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Account_RegisterResult) Reset()         { *m = Account_RegisterResult{} }
func (m *Account_RegisterResult) String() string { return proto.CompactTextString(m) }
func (*Account_RegisterResult) ProtoMessage()    {}

const Default_Account_RegisterResult_Pid AccountMsgID = AccountMsgID_Msg_RegisterResult

func (m *Account_RegisterResult) GetPid() AccountMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Account_RegisterResult_Pid
}

func (m *Account_RegisterResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 发送给game消息
type Account_GetGameAccount struct {
	Pid              *AccountMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.AccountMsgID,def=100" json:"pid,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Account_GetGameAccount) Reset()         { *m = Account_GetGameAccount{} }
func (m *Account_GetGameAccount) String() string { return proto.CompactTextString(m) }
func (*Account_GetGameAccount) ProtoMessage()    {}

const Default_Account_GetGameAccount_Pid AccountMsgID = AccountMsgID_Msg_GetGameAccount

func (m *Account_GetGameAccount) GetPid() AccountMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Account_GetGameAccount_Pid
}

type Account_GameResult struct {
	Pid              *AccountMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.AccountMsgID,def=101" json:"pid,omitempty"`
	Count            *int32        `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	GameAddress      *string       `protobuf:"bytes,3,opt,name=game_address" json:"game_address,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Account_GameResult) Reset()         { *m = Account_GameResult{} }
func (m *Account_GameResult) String() string { return proto.CompactTextString(m) }
func (*Account_GameResult) ProtoMessage()    {}

const Default_Account_GameResult_Pid AccountMsgID = AccountMsgID_Msg_GameResult

func (m *Account_GameResult) GetPid() AccountMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Account_GameResult_Pid
}

func (m *Account_GameResult) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *Account_GameResult) GetGameAddress() string {
	if m != nil && m.GameAddress != nil {
		return *m.GameAddress
	}
	return ""
}

type Account_NoteGame struct {
	Pid              *AccountMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.AccountMsgID,def=102" json:"pid,omitempty"`
	PlayerId         *int32        `protobuf:"varint,2,opt,name=player_id" json:"player_id,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Account_NoteGame) Reset()         { *m = Account_NoteGame{} }
func (m *Account_NoteGame) String() string { return proto.CompactTextString(m) }
func (*Account_NoteGame) ProtoMessage()    {}

const Default_Account_NoteGame_Pid AccountMsgID = AccountMsgID_Msg_NoteGame

func (m *Account_NoteGame) GetPid() AccountMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Account_NoteGame_Pid
}

func (m *Account_NoteGame) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type Game struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}

type Game_GetType struct {
	Pid              *GameMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.GameMsgID,def=1000" json:"pid,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Game_GetType) Reset()         { *m = Game_GetType{} }
func (m *Game_GetType) String() string { return proto.CompactTextString(m) }
func (*Game_GetType) ProtoMessage()    {}

const Default_Game_GetType_Pid GameMsgID = GameMsgID_Game_Msg_GetType

func (m *Game_GetType) GetPid() GameMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Game_GetType_Pid
}

type Game_BaseRole struct {
	PlayerId         *int32  `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	Nick             *string `protobuf:"bytes,2,req,name=nick" json:"nick,omitempty"`
	Gender           *bool   `protobuf:"varint,3,req,name=gender" json:"gender,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Game_BaseRole) Reset()         { *m = Game_BaseRole{} }
func (m *Game_BaseRole) String() string { return proto.CompactTextString(m) }
func (*Game_BaseRole) ProtoMessage()    {}

func (m *Game_BaseRole) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *Game_BaseRole) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

func (m *Game_BaseRole) GetGender() bool {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return false
}

type Game_RegisterRole struct {
	Pid              *GameMsgID     `protobuf:"varint,1,opt,name=pid,enum=protocol.GameMsgID,def=1001" json:"pid,omitempty"`
	Info             *Game_BaseRole `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Game_RegisterRole) Reset()         { *m = Game_RegisterRole{} }
func (m *Game_RegisterRole) String() string { return proto.CompactTextString(m) }
func (*Game_RegisterRole) ProtoMessage()    {}

const Default_Game_RegisterRole_Pid GameMsgID = GameMsgID_Game_Msg_RegisterRole

func (m *Game_RegisterRole) GetPid() GameMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Game_RegisterRole_Pid
}

func (m *Game_RegisterRole) GetInfo() *Game_BaseRole {
	if m != nil {
		return m.Info
	}
	return nil
}

type Game_RegisterRoleResult struct {
	Pid              *GameMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.GameMsgID,def=1002" json:"pid,omitempty"`
	Result           *int32     `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Game_RegisterRoleResult) Reset()         { *m = Game_RegisterRoleResult{} }
func (m *Game_RegisterRoleResult) String() string { return proto.CompactTextString(m) }
func (*Game_RegisterRoleResult) ProtoMessage()    {}

const Default_Game_RegisterRoleResult_Pid GameMsgID = GameMsgID_Game_Msg_RegisterRoleResult

func (m *Game_RegisterRoleResult) GetPid() GameMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Game_RegisterRoleResult_Pid
}

func (m *Game_RegisterRoleResult) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type Game_GetRoleInfo struct {
	Pid              *GameMsgID `protobuf:"varint,1,opt,name=pid,enum=protocol.GameMsgID,def=1003" json:"pid,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Game_GetRoleInfo) Reset()         { *m = Game_GetRoleInfo{} }
func (m *Game_GetRoleInfo) String() string { return proto.CompactTextString(m) }
func (*Game_GetRoleInfo) ProtoMessage()    {}

const Default_Game_GetRoleInfo_Pid GameMsgID = GameMsgID_Game_Msg_GetRoleInfo

func (m *Game_GetRoleInfo) GetPid() GameMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Game_GetRoleInfo_Pid
}

type Game_RoleInfo struct {
	BaseRole         *Game_BaseRole `protobuf:"bytes,1,opt,name=base_role" json:"base_role,omitempty"`
	EquipIds         []int32        `protobuf:"varint,2,rep,name=equip_ids" json:"equip_ids,omitempty"`
	TaskIds          []int32        `protobuf:"varint,3,rep,name=task_ids" json:"task_ids,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Game_RoleInfo) Reset()         { *m = Game_RoleInfo{} }
func (m *Game_RoleInfo) String() string { return proto.CompactTextString(m) }
func (*Game_RoleInfo) ProtoMessage()    {}

func (m *Game_RoleInfo) GetBaseRole() *Game_BaseRole {
	if m != nil {
		return m.BaseRole
	}
	return nil
}

func (m *Game_RoleInfo) GetEquipIds() []int32 {
	if m != nil {
		return m.EquipIds
	}
	return nil
}

func (m *Game_RoleInfo) GetTaskIds() []int32 {
	if m != nil {
		return m.TaskIds
	}
	return nil
}

type Game_RoleInfoResult struct {
	Pid              *GameMsgID     `protobuf:"varint,1,opt,name=pid,enum=protocol.GameMsgID,def=1004" json:"pid,omitempty"`
	RoleInfo         *Game_RoleInfo `protobuf:"bytes,2,opt,name=role_info" json:"role_info,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Game_RoleInfoResult) Reset()         { *m = Game_RoleInfoResult{} }
func (m *Game_RoleInfoResult) String() string { return proto.CompactTextString(m) }
func (*Game_RoleInfoResult) ProtoMessage()    {}

const Default_Game_RoleInfoResult_Pid GameMsgID = GameMsgID_Game_Msg_RoleInfoResult

func (m *Game_RoleInfoResult) GetPid() GameMsgID {
	if m != nil && m.Pid != nil {
		return *m.Pid
	}
	return Default_Game_RoleInfoResult_Pid
}

func (m *Game_RoleInfoResult) GetRoleInfo() *Game_RoleInfo {
	if m != nil {
		return m.RoleInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.AccountMsgID", AccountMsgID_name, AccountMsgID_value)
	proto.RegisterEnum("protocol.GameMsgID", GameMsgID_name, GameMsgID_value)
}
